### ISSUE TITLE
代码报错

### ISSUE THREAD

**Issue by F-ops286** [jinpeng01/LANER#1]
您好 作者 我认为您的论文思路非常新颖 最近在尝试复现代码 但是遇到了一个报错问题 您是否遇到过这种问题  望回复 感激不尽
Traceback (most recent call last):
  File "main.py", line 176, in <module>
    train(params)
  File "main.py", line 122, in train
    f1_train, report_results = trainer.evaluate(dataloader_train, params.tgt_dm, use_bilstm=params.bilstm)
  File "/home/nlp/nlp/LANER-main/LANER-main/src/trainer.py", line 116, in evaluate
    report = classification_report(gold_tokens, pred_tokens, digits=4)
  File "/home/nlp/anaconda3/envs/LANER/lib/python3.7/site-packages/seqeval/metrics/sequence_labeling.py", line 697, in classification_report
    suffix=suffix
  File "/home/nlp/anaconda3/envs/LANER/lib/python3.7/site-packages/seqeval/metrics/sequence_labeling.py", line 139, in precision_recall_fscore_support
    extract_tp_actual_correct=extract_tp_actual_correct
  File "/home/nlp/anaconda3/envs/LANER/lib/python3.7/site-packages/seqeval/metrics/v1.py", line 122, in _precision_recall_fscore_support
    check_consistent_length(y_true, y_pred)
  File "/home/nlp/anaconda3/envs/LANER/lib/python3.7/site-packages/seqeval/metrics/v1.py", line 97, in check_consistent_length
    raise TypeError('Found input variables without list of list.')
TypeError: Found input variables without list of list.
train.sh: line 15: --ckpt: command not found

**Comment by jinpeng01** [comment]
您好，请问你是跑的DAPT的版本还是Bert-base版本？

**Comment by jinpeng01** [comment]
你再查看一下seqeval的版本，我用的版本是seqeval==0.0.12
